package distrokid

var ElectronicGenres = []string{
	"Big Room",
	"Breaks",
	"Chill Out",
	"Deep House",
	"Drum & Bass",
	"Dubstep",
	"Electro House",
	"Electronica / Downtempo",
	"Funk / Soul / Disco",
	"Glitch Hop",
	"Hard Dance",
	"Hardcore / Hard Techno",
	"Hip-Hop / R&B",
	"House",
	"Indie Dance / Nu Disco",
	"Minimal / Deep Tech",
	"Progressive House",
	"Psy-Trance",
	"Reggae / Dancehall / Dub",
	"Tech House",
	"Techno",
	"Trance",
}

var Genres = []string{
	"Afrobeat",
	"Afropop",
	"Alternative",
	"Big Band",
	"Blues",
	"Children's Music",
	"Christian/Gospel",
	"Classical",
	"Comedy",
	"Country",
	"Dance",
	"Fitness & Workout",
	"Folk",
	"French Pop",
	"German Folk",
	"German Pop",
	"Hip Hop/Rap",
	"Holiday",
	"J-Pop",
	"Jazz",
	"K-Pop",
	"Latin",
	"Latin Urban",
	"Metal",
	"New Age",
	"Pop",
	"Punk",
	"R&B/Soul",
	"Reggae",
	"Rock",
	"Singer/Songwriter",
	"Soundtrack",
	"Spoken Word",
	"Vocal",
	"World",
	"Electronic:Big Room",
	"Electronic:Breaks",
	"Electronic:Chill Out",
	"Electronic:Deep House",
	"Electronic:Drum & Bass",
	"Electronic:Dubstep",
	"Electronic:Electro House",
	"Electronic:Electronica / Downtempo",
	"Electronic:Funk / Soul / Disco",
	"Electronic:Glitch Hop",
	"Electronic:Hard Dance",
	"Electronic:Hardcore / Hard Techno",
	"Electronic:Hip-Hop / R&B",
	"Electronic:House",
	"Electronic:Indie Dance / Nu Disco",
	"Electronic:Minimal / Deep Tech",
	"Electronic:Progressive House",
	"Electronic:Psy-Trance",
	"Electronic:Reggae / Dancehall / Dub",
	"Electronic:Tech House",
	"Electronic:Techno",
	"Electronic:Trance",
}
