package jamendo

var Genres = []string{
	"8bit",
	"acidhouse",
	"acidjazz",
	"adultcontemporary",
	"African",
	"afro (african)",
	"afro-cuban jazz (afrocubanjazz)",
	"afrobeat",
	"afrocubanjazz",
	"afropop",
	"Alternative Pop (alternativepop)",
	"alternativemetal",
	"alternativepop",
	"alternativernb",
	"alternativerock",
	"ambiance (ambient)",
	"ambiant (ambient)",
	"Ambient",
	"ambientdub",
	"americana",
	"americannative",
	"artrock",
	"Asian",
	"Avant-garde (avantgarde)",
	"avantgarde",
	"bachata",
	"balkan",
	"baroque",
	"batucada",
	"Bebop",
	"blackmetal",
	"bluegrass",
	"Blues",
	"bluesrock",
	"bluesy (blues)",
	"bolero",
	"bossa (bossanova)",
	"bossanova",
	"Breakbeat",
	"Breakcore",
	"britpop",
	"cabaret",
	"calypso",
	"Celtic",
	"celtique (celtic)",
	"chamber",
	"chansonfrancaise",
	"chill (chillout)",
	"chillhop",
	"Chillout",
	"chillwave",
	"chiptune (8bit)",
	"choral",
	"christian",
	"classic (classical)",
	"Classical",
	"classicrock",
	"classique (classical)",
	"cocktail jazz (smoothjazz)",
	"cocktailjazz (smoothjazz)",
	"coldwave",
	"contemporarypiano",
	"Corporate",
	"Country",
	"countryrock",
	"crust",
	"cumbia",
	"Dance",
	"Dancehall",
	"dancepop",
	"Dark Wave (darkwave)",
	"darkambient",
	"darkstep",
	"darkwave",
	"death (deathmetal)",
	"deathcore",
	"deathmetal",
	"deephouse",
	"Disco",
	"dnb (drumnbass)",
	"doom (doommetal)",
	"doommetal",
	"Downtempo",
	"dreampop",
	"Drone",
	"drumandbass (drumnbass)",
	"drumbass (drumnbass)",
	"drumnbass",
	"Dub",
	"Dubstep",
	"Easy-listening (easylistening)",
	"easylistening",
	"EBM",
	"EDM",
	"electrofunk",
	"electrohouse",
	"Electronic",
	"electronica",
	"electronik (electronic)",
	"electronique (electronic)",
	"Electropop",
	"electropunk",
	"electrorock",
	"electroswing",
	"elettronica (electronic)",
	"emo",
	"Eurodance",
	"Experimental",
	"experimentale (experimental)",
	"fado",
	"fanfare",
	"filmscore",
	"Flamenco",
	"Folk",
	"folklore",
	"freejazz",
	"frenchpop",
	"Funk",
	"funky (funk)",
	"futurebass",
	"gangsta (gangstarap)",
	"gangstarap",
	"Garage",
	"Gipsy (gypsy)",
	"glam",
	"Glitch",
	"Gospel",
	"Gothic",
	"gothique (gothic)",
	"grime",
	"grind (grindcore)",
	"Grindcore",
	"groovemetal",
	"Grunge",
	"Gypsy",
	"Hardcore",
	"hardcorepunk",
	"hardrock",
	"hardstep",
	"heavymetal",
	"hiphop",
	"House",
	"IDM",
	"indian",
	"Indie",
	"indiepop",
	"indierock",
	"indierock (indie)",
	"indietronica",
	"Industrial",
	"industrialmetal",
	"industrialrock",
	"intro",
	"Jazz",
	"Jazz Rap (jazzrap)",
	"jazzfunk",
	"jazzfusion",
	"jazzrap",
	"Jingle",
	"jpop",
	"Jungle",
	"Kids/Quirky (kidsquirky)",
	"kidsquirky",
	"klezmer",
	"kpop",
	"krautrock",
	"Latin",
	"latinjazz",
	"latino (latin)",
	"lofi",
	"logo",
	"loop",
	"mambo",
	"Manouche",
	"march",
	"mariachi",
	"mathcore",
	"mathrock",
	"medieval",
	"merengue",
	"Metal",
	"Metalcore",
	"middleeastern",
	"musicbed",
	"nativeamerican (americannative)",
	"neoclassical",
	"neurofunk",
	"newage",
	"newwave",
	"noisepop",
	"noiserock",
	"nujazz",
	"numetal",
	"opera",
	"Oriental",
	"Pop",
	"Pop Rock (poprock)",
	"poppunk",
	"poprock",
	"postgrunge",
	"posthardcore",
	"postmetal",
	"postpunk",
	"postrock",
	"powermetal",
	"production",
	"progressive rock (progressiverock)",
	"progressivehouse",
	"progressivemetal",
	"progressiverock",
	"psychedelicrock",
	"Psytrance",
	"Punk",
	"Ragga",
	"raggae (reggae)",
	"ragtime",
	"rai",
	"rap",
	"Rap (hiphop)",
	"Reggae",
	"reggaeton",
	"rhythmandblues (rnb)",
	"rnb",
	"Rock",
	"rockabilly",
	"rockandroll (rocknroll)",
	"rockindependant (indie)",
	"rocknroll",
	"rocksteady",
	"rumba",
	"salsa",
	"Samba",
	"shoegaze",
	"Singer-Songwriter (singersongwriter)",
	"singersongwriter",
	"Ska",
	"skapunk",
	"sludge",
	"smoothjazz",
	"songwriter (singersongwriter)",
	"songwriting (singersongwriter)",
	"Soul",
	"Soundtrack (filmscore)",
	"southernrock",
	"spacerock",
	"sperimental (experimental)",
	"sperimentale (experimental)",
	"spokenword",
	"stinger",
	"stoner",
	"surf (surfrock)",
	"surfrock",
	"swing",
	"Symphonic",
	"symphonique (symphonic)",
	"Synthpop",
	"synthwave",
	"Tango",
	"Techno",
	"thrash (thrashmetal)",
	"thrashmetal",
	"Trailer",
	"trailermusic (trailer)",
	"Trance",
	"trap",
	"trash (thrashmetal)",
	"trashmetal (thrashmetal)",
	"Tribal",
	"tribe (tribal)",
	"triphop",
	"tropicalhouse",
	"waltz",
	"Western",
	"World",
	"worldmusic (world)",
	"zouk",
}

var Tags = []string{
	"Accordion",
	"acousticbass",
	"acousticbassguitar (acousticbass)",
	"acousticguitar",
	"aggressive",
	"alboka",
	"Alphorn",
	"alto (viola)",
	"angry",
	"Bagpipes",
	"baixo (bass)",
	"bajo (bass)",
	"Balafon",
	"Balalaika",
	"bandolim (mandolin)",
	"bandone (bandoneon)",
	"bandoneã³n (bandoneon)",
	"Bandoneon",
	"Banjo",
	"Bass",
	"basse (bass)",
	"bassguitar (bass)",
	"Bassoon",
	"bateria (drums)",
	"batterie (drums)",
	"bazooka",
	"beatbox",
	"Bell (bells)",
	"bells",
	"Berimbau",
	"blissful (happy)",
	"bodhr (bodhran)",
	"bodhrã¡n (bodhran)",
	"Bodhran",
	"bombard (bombarde)",
	"Bombarde",
	"Bongo",
	"bongodrum (bongo)",
	"bongos (bongo)",
	"brass",
	"Bugle",
	"caj (cajon)",
	"cajã³n (cajon)",
	"Cajon",
	"Calm",
	"Calm (peaceful)",
	"calme (peaceful)",
	"Carillon",
	"Castanets",
	"celesta",
	"Cello",
	"chapmanstick",
	"Charango",
	"cheerful",
	"chitarra",
	"Cimbalom",
	"Cittern",
	"claps",
	"Clarinet",
	"clarinette (clarinet)",
	"classicalguitar",
	"clavecin (harpsichord)",
	"Clavichord",
	"clavicordio (clavichord)",
	"claviers (synthesizer)",
	"Computer",
	"computers (computer)",
	"Concertina",
	"Conga",
	"congas (conga)",
	"contrabajo (doublebass)",
	"contrebasse (doublebass)",
	"Cowbell",
	"cu (cuica)",
	"cuã&shy;ca (cuica)",
	"cuica",
	"Cymbal",
	"Dark",
	"dholak",
	"Didgeridoo",
	"Djembe",
	"Double Bass (doublebass)",
	"doublebass",
	"dramatic",
	"dreamy",
	"drole (funny)",
	"drum (drums)",
	"drummachine",
	"Drums",
	"duduk",
	"Dunun",
	"dynamic (energetic)",
	"Electric Guitar (electricguitar)",
	"electricbass",
	"electricguitar",
	"electricguitars (electricguitar)",
	"electricorgan",
	"electricpiano",
	"electro amplified (electroamplified)",
	"electroamplified",
	"electronicorgan",
	"Emotion (emotional)",
	"emotional",
	"Energetic",
	"energie (energetic)",
	"energy (energetic)",
	"Epic",
	"Erhu",
	"erotic",
	"erotic (sexy)",
	"euphonium",
	"exciting",
	"Fiddle",
	"flauta (flute)",
	"flauto (flute)",
	"Flugelhorn",
	"Flute",
	"flutes (flute)",
	"fortepian (piano)",
	"frenchhorn (horn)",
	"fun",
	"funny",
	"gã¼iro (guiro)",
	"gitarre",
	"glassharmonica",
	"Glockenspiel",
	"gong",
	"Groove (groovy)",
	"groovy",
	"Guiro",
	"guitar",
	"guitare (guitar)",
	"guitareelectrique (electricguitar)",
	"guitares (guitar)",
	"guitarra (guitar)",
	"guitarras (guitar)",
	"guitars (guitar)",
	"Hammond",
	"hammondorgan (hammond)",
	"hamonica (harmonica)",
	"handpan",
	"Happy",
	"Harmonica",
	"Harmonium",
	"Harp",
	"harpe (harp)",
	"Harpsichord",
	"Horn",
	"horns (horn)",
	"inspiration (inspirational)",
	"inspirational",
	"Inspiring (inspirational)",
	"intimate",
	"introspective",
	"Jew's-harp (jewsharp)",
	"jewsharp",
	"joyful (happy)",
	"Kalimba",
	"Kanun",
	"Kazoo",
	"Keyboard (synthesizer)",
	"keyboardinstrument (synthesizer)",
	"keyboards (synthesizer)",
	"keys (synthesizer)",
	"klavier (piano)",
	"Kora",
	"Koto",
	"likembe (mbira)",
	"Lute",
	"majestic",
	"Mandola",
	"Mandolin",
	"mandolina (mandolin)",
	"mandoline (mandolin)",
	"marã&shy;mbula (kalimba)",
	"Marimba",
	"mbira",
	"Mbira (kalimba)",
	"Meditative",
	"melancholic",
	"Melancholy (melancholic)",
	"melancolic (melancholic)",
	"melancolique (melancholic)",
	"Mellophone",
	"Mellotron",
	"Melodica",
	"Metallophone",
	"motivation (motivational)",
	"Motivational",
	"musicalsaw",
	"Ney",
	"Nostalgic",
	"nyckelharpa",
	"Oboe",
	"Ocarina",
	"orchestra",
	"Organ",
	"Oud",
	"Pan Flute (panflute)",
	"Pandeiro",
	"panflute",
	"Peaceful",
	"Percussion",
	"percussions (percussion)",
	"Piano",
	"pianoforte (piano)",
	"pianos (piano)",
	"Piccolo",
	"Pipe Organ (organ)",
	"pipeorgan",
	"positive (upbeat)",
	"powerful",
	"quirky",
	"rainstick",
	"relax (peaceful)",
	"relaxant (peaceful)",
	"relaxation (peaceful)",
	"Relaxed (peaceful)",
	"Relaxing",
	"Relaxing (peaceful)",
	"romance (romantic)",
	"Romantic",
	"romantique (romantic)",
	"Sad",
	"Sampler",
	"santoor (santur)",
	"Santur",
	"sarangi",
	"satirical",
	"sax (saxophone)",
	"Saxophone",
	"scary",
	"sensual (sexy)",
	"sentimental",
	"serene",
	"sexy",
	"shaker",
	"Shamisen",
	"Shekere",
	"Singing bowl (singingbowl)",
	"singingbowl",
	"Sitar",
	"Slide Guitar (slideguitar)",
	"slideguitar",
	"solemn",
	"steel-stringacousticguitar (acousticguitar)",
	"steelguitar (slideguitar)",
	"Steelpan",
	"strange",
	"string (strings)",
	"strings",
	"surdo",
	"synth (synthesizer)",
	"synthe (synthesizer)",
	"Synthesizer",
	"synthesizers (synthesizer)",
	"synthetiseur (synthesizer)",
	"synthetiseurs (synthesizer)",
	"synthetizer (synthesizer)",
	"synths (synthesizer)",
	"Tambourine",
	"Tambura",
	"tamtam",
	"Tamtam (gong)",
	"tender",
	"tense",
	"theatrical",
	"Theremin",
	"thermin (theremin)",
	"tibetan bowls (tibetanbowls)",
	"tibetanbowls",
	"Timpani",
	"tinwhistle",
	"Triangle",
	"trippy",
	"Trombone",
	"trompette (trumpet)",
	"Trumpet",
	"Tuba",
	"tubularbell",
	"Udu",
	"Ukulele",
	"upbeat",
	"Uplifting",
	"veryhappy",
	"verysad",
	"Vibraphone",
	"Viola",
	"Violin",
	"violine (violin)",
	"violino (violin)",
	"violins (violin)",
	"violon (violin)",
	"violoncelle (cello)",
	"violons (violin)",
	"vocoder",
	"Washboard",
	"Weird (strange)",
	"whistling",
	"Wind",
	"woodblock",
	"woodwind",
	"Xylophone",
	"zen (meditative)",
}

var convert = map[string]string{
	// genres
	"alternative rock":  "alternativerock",
	"chill":             "chill (chillout)",
	"easy listening":    "easylistening",
	"electro":           "Electronic",
	"fusion":            "jazzfusion",
	"heavy metal":       "heavymetal",
	"indie rock":        "indierock",
	"new age":           "newage",
	"new-age":           "newage",
	"pop rock":          "poprock",
	"progressive metal": "progressivemetal",
	"progressive rock":  "progressiverock",
	"r&b":               "rnb",
	// instruments
	"bass guitar":       "Bass",
	"bass synth":        "bass synthesizer",
	"brass instruments": "brass",
	"brass section":     "brass",
	"drum machine":      "drummachine",
	"electric guitar":   "Electric Guitar (electricguitar)",
	"electric piano":    "electricpiano",
	"keyboard":          "Keyboard (synthesizer)",
	"synth":             "synth (synthesizer)",
	// moods
	"calming":       "Calm",
	"dynamic":       "dynamic (energetic)",
	"innovative":    "",
	"intense":       "",
	"intriguing":    "",
	"melancholy":    "",
	"mellow":        "",
	"mysterious":    "",
	"playful":       "",
	"reflective":    "",
	"relaxed":       "",
	"seductive":     "",
	"sensual":       "",
	"smooth":        "",
	"soothing":      "",
	"sophisticated": "",
	"soulful":       "",
	"spacey":        "",
	"sublime":       "",
	"tranquil":      "",
	"triumphant":    "",
	// styles
	"abstract":                  "",
	"acid jazz":                 "",
	"acoustic":                  "",
	"acoustic blues":            "",
	"acoustic guitar":           "",
	"acoustic jazz":             "",
	"acoustic pop":              "",
	"alternative":               "",
	"ambient electronic":        "",
	"ambient house":             "",
	"ambient jazz":              "",
	"ambient pop":               "",
	"atmospheric":               "",
	"background music":          "",
	"ballad":                    "",
	"beautiful":                 "",
	"big band":                  "",
	"blues fusion":              "",
	"blues rock":                "",
	"chamber jazz":              "",
	"chamber music":             "",
	"chicago blues":             "",
	"chill out":                 "",
	"chill-out":                 "",
	"cinematic":                 "",
	"classical crossover":       "",
	"contemplative":             "",
	"contemporary":              "",
	"contemporary classical":    "",
	"contemporary instrumental": "",
	"contemporary jazz":         "",
	"cool jazz":                 "",
	"deep house":                "",
	"delta blues":               "",
	"doom metal":                "",
	"dream pop":                 "",
	"drum focused":              "",
	"drum and bass":             "",
	"electric blues":            "",
	"electro funk":              "",
	"electronic jazz":           "",
	"electronic rock":           "",
	"folk blues":                "",
	"folk jazz":                 "",
	"folk rock":                 "",
	"fusion jazz":               "",
	"future bass":               "",
	"futuristic":                "",
	"gothic metal":              "",
	"guitar jazz":               "",
	"guitar solo":               "",
	"hard bop":                  "",
	"hard rock":                 "",
	"indie electronic":          "",
	"indie folk":                "",
	"instrumental rock":         "",
	"latin jazz":                "",
	"lounge":                    "",
	"mellow jazz":               "",
	"minimal":                   "",
	"minimalism":                "",
	"minimalist":                "",
	"modal jazz":                "",
	"neo-classical":             "",
	"neo-soul":                  "",
	"nu disco":                  "",
	"nu jazz":                   "",
	"nu-disco":                  "",
	"orchestral":                "",
	"piano blues":               "",
	"piano jazz":                "",
	"piano rock":                "",
	"post-rock":                 "",
	"power metal":               "",
	"progressive":               "",
	"progressive electronic":    "",
	"psybient":                  "",
	"psychedelic":               "",
	"psychedelic rock":          "",
	"ragtime jazz":              "",
	"retro":                     "",
	"retrowave":                 "",
	"sadcore":                   "",
	"singer-songwriter":         "",
	"smooth jazz":               "",
	"soft rock":                 "",
	"soul jazz":                 "",
	"soulful blues":             "",
	"space":                     "",
	"space rock":                "",
	"symphonic metal":           "",
	"thrash metal":              "",
	"trip hop":                  "",
	"trip-hop":                  "",
	"acoustic rock":             "",
	"instrumental":              "",
}
