package jamendo

import "strings"

var Genres = []string{
	"8bit",
	"acidhouse",
	"acidjazz",
	"adultcontemporary",
	"African",
	"afro (african)",
	"afro-cuban jazz (afrocubanjazz)",
	"afrobeat",
	"afrocubanjazz",
	"afropop",
	"Alternative Pop (alternativepop)",
	"alternativemetal",
	"alternativepop",
	"alternativernb",
	"alternativerock",
	"ambiance (ambient)",
	"ambiant (ambient)",
	"Ambient",
	"ambientdub",
	"americana",
	"americannative",
	"artrock",
	"Asian",
	"Avant-garde (avantgarde)",
	"avantgarde",
	"bachata",
	"balkan",
	"baroque",
	"batucada",
	"Bebop",
	"blackmetal",
	"bluegrass",
	"Blues",
	"bluesrock",
	"bluesy (blues)",
	"bolero",
	"bossa (bossanova)",
	"bossanova",
	"Breakbeat",
	"Breakcore",
	"britpop",
	"cabaret",
	"calypso",
	"Celtic",
	"celtique (celtic)",
	"chamber",
	"chansonfrancaise",
	"chill (chillout)",
	"chillhop",
	"Chillout",
	"chillwave",
	"chiptune (8bit)",
	"choral",
	"christian",
	"classic (classical)",
	"Classical",
	"classicrock",
	"classique (classical)",
	"cocktail jazz (smoothjazz)",
	"cocktailjazz (smoothjazz)",
	"coldwave",
	"contemporarypiano",
	"Corporate",
	"Country",
	"countryrock",
	"crust",
	"cumbia",
	"Dance",
	"Dancehall",
	"dancepop",
	"Dark Wave (darkwave)",
	"darkambient",
	"darkstep",
	"darkwave",
	"death (deathmetal)",
	"deathcore",
	"deathmetal",
	"deephouse",
	"Disco",
	"dnb (drumnbass)",
	"doom (doommetal)",
	"doommetal",
	"Downtempo",
	"dreampop",
	"Drone",
	"drumandbass (drumnbass)",
	"drumbass (drumnbass)",
	"drumnbass",
	"Dub",
	"Dubstep",
	"Easy-listening (easylistening)",
	"easylistening",
	"EBM",
	"EDM",
	"electrofunk",
	"electrohouse",
	"Electronic",
	"electronica",
	"electronik (electronic)",
	"electronique (electronic)",
	"Electropop",
	"electropunk",
	"electrorock",
	"electroswing",
	"elettronica (electronic)",
	"emo",
	"Eurodance",
	"Experimental",
	"experimentale (experimental)",
	"fado",
	"fanfare",
	"filmscore",
	"Flamenco",
	"Folk",
	"folklore",
	"freejazz",
	"frenchpop",
	"Funk",
	"funky (funk)",
	"futurebass",
	"gangsta (gangstarap)",
	"gangstarap",
	"Garage",
	"Gipsy (gypsy)",
	"glam",
	"Glitch",
	"Gospel",
	"Gothic",
	"gothique (gothic)",
	"grime",
	"grind (grindcore)",
	"Grindcore",
	"groovemetal",
	"Grunge",
	"Gypsy",
	"Hardcore",
	"hardcorepunk",
	"hardrock",
	"hardstep",
	"heavymetal",
	"hiphop",
	"House",
	"IDM",
	"indian",
	"Indie",
	"indiepop",
	"indierock",
	"indierock (indie)",
	"indietronica",
	"Industrial",
	"industrialmetal",
	"industrialrock",
	"intro",
	"Jazz",
	"Jazz Rap (jazzrap)",
	"jazzfunk",
	"jazzfusion",
	"jazzrap",
	"Jingle",
	"jpop",
	"Jungle",
	"Kids/Quirky (kidsquirky)",
	"kidsquirky",
	"klezmer",
	"kpop",
	"krautrock",
	"Latin",
	"latinjazz",
	"latino (latin)",
	"lofi",
	"logo",
	"loop",
	"mambo",
	"Manouche",
	"march",
	"mariachi",
	"mathcore",
	"mathrock",
	"medieval",
	"merengue",
	"Metal",
	"Metalcore",
	"middleeastern",
	"musicbed",
	"nativeamerican (americannative)",
	"neoclassical",
	"neurofunk",
	"newage",
	"newwave",
	"noisepop",
	"noiserock",
	"nujazz",
	"numetal",
	"opera",
	"Oriental",
	"Pop",
	"Pop Rock (poprock)",
	"poppunk",
	"poprock",
	"postgrunge",
	"posthardcore",
	"postmetal",
	"postpunk",
	"postrock",
	"powermetal",
	"production",
	"progressive rock (progressiverock)",
	"progressivehouse",
	"progressivemetal",
	"progressiverock",
	"psychedelicrock",
	"Psytrance",
	"Punk",
	"Ragga",
	"raggae (reggae)",
	"ragtime",
	"rai",
	"rap",
	"Rap (hiphop)",
	"Reggae",
	"reggaeton",
	"rhythmandblues (rnb)",
	"rnb",
	"Rock",
	"rockabilly",
	"rockandroll (rocknroll)",
	"rockindependant (indie)",
	"rocknroll",
	"rocksteady",
	"rumba",
	"salsa",
	"Samba",
	"shoegaze",
	"Singer-Songwriter (singersongwriter)",
	"singersongwriter",
	"Ska",
	"skapunk",
	"sludge",
	"smoothjazz",
	"songwriter (singersongwriter)",
	"songwriting (singersongwriter)",
	"Soul",
	"Soundtrack (filmscore)",
	"southernrock",
	"spacerock",
	"sperimental (experimental)",
	"sperimentale (experimental)",
	"spokenword",
	"stinger",
	"stoner",
	"surf (surfrock)",
	"surfrock",
	"swing",
	"Symphonic",
	"symphonique (symphonic)",
	"Synthpop",
	"synthwave",
	"Tango",
	"Techno",
	"thrash (thrashmetal)",
	"thrashmetal",
	"Trailer",
	"trailermusic (trailer)",
	"Trance",
	"trap",
	"trash (thrashmetal)",
	"trashmetal (thrashmetal)",
	"Tribal",
	"tribe (tribal)",
	"triphop",
	"tropicalhouse",
	"waltz",
	"Western",
	"World",
	"worldmusic (world)",
	"zouk",
}

var Tags = []string{
	"Accordion",
	"acousticbass",
	"acousticbassguitar (acousticbass)",
	"acousticguitar",
	"aggressive",
	"alboka",
	"Alphorn",
	"alto (viola)",
	"angry",
	"Bagpipes",
	"baixo (bass)",
	"bajo (bass)",
	"Balafon",
	"Balalaika",
	"bandolim (mandolin)",
	"bandone (bandoneon)",
	"bandoneã³n (bandoneon)",
	"Bandoneon",
	"Banjo",
	"Bass",
	"basse (bass)",
	"bassguitar (bass)",
	"Bassoon",
	"bateria (drums)",
	"batterie (drums)",
	"bazooka",
	"beatbox",
	"Bell (bells)",
	"bells",
	"Berimbau",
	"blissful (happy)",
	"bodhr (bodhran)",
	"bodhrã¡n (bodhran)",
	"Bodhran",
	"bombard (bombarde)",
	"Bombarde",
	"Bongo",
	"bongodrum (bongo)",
	"bongos (bongo)",
	"brass",
	"Bugle",
	"caj (cajon)",
	"cajã³n (cajon)",
	"Cajon",
	"Calm",
	"Calm (peaceful)",
	"calme (peaceful)",
	"Carillon",
	"Castanets",
	"celesta",
	"Cello",
	"chapmanstick",
	"Charango",
	"cheerful",
	"chitarra",
	"Cimbalom",
	"Cittern",
	"claps",
	"Clarinet",
	"clarinette (clarinet)",
	"classicalguitar",
	"clavecin (harpsichord)",
	"Clavichord",
	"clavicordio (clavichord)",
	"claviers (synthesizer)",
	"Computer",
	"computers (computer)",
	"Concertina",
	"Conga",
	"congas (conga)",
	"contrabajo (doublebass)",
	"contrebasse (doublebass)",
	"Cowbell",
	"cu (cuica)",
	"cuã&shy;ca (cuica)",
	"cuica",
	"Cymbal",
	"Dark",
	"dholak",
	"Didgeridoo",
	"Djembe",
	"Double Bass (doublebass)",
	"doublebass",
	"dramatic",
	"dreamy",
	"drole (funny)",
	"drum (drums)",
	"drummachine",
	"Drums",
	"duduk",
	"Dunun",
	"dynamic (energetic)",
	"Electric Guitar (electricguitar)",
	"electricbass",
	"electricguitar",
	"electricguitars (electricguitar)",
	"electricorgan",
	"electricpiano",
	"electro amplified (electroamplified)",
	"electroamplified",
	"electronicorgan",
	"Emotion (emotional)",
	"emotional",
	"Energetic",
	"energie (energetic)",
	"energy (energetic)",
	"Epic",
	"Erhu",
	"erotic",
	"erotic (sexy)",
	"euphonium",
	"exciting",
	"Fiddle",
	"flauta (flute)",
	"flauto (flute)",
	"Flugelhorn",
	"Flute",
	"flutes (flute)",
	"fortepian (piano)",
	"frenchhorn (horn)",
	"fun",
	"funny",
	"gã¼iro (guiro)",
	"gitarre",
	"glassharmonica",
	"Glockenspiel",
	"gong",
	"Groove (groovy)",
	"groovy",
	"Guiro",
	"guitar",
	"guitare (guitar)",
	"guitareelectrique (electricguitar)",
	"guitares (guitar)",
	"guitarra (guitar)",
	"guitarras (guitar)",
	"guitars (guitar)",
	"Hammond",
	"hammondorgan (hammond)",
	"hamonica (harmonica)",
	"handpan",
	"Happy",
	"Harmonica",
	"Harmonium",
	"Harp",
	"harpe (harp)",
	"Harpsichord",
	"Horn",
	"horns (horn)",
	"inspiration (inspirational)",
	"inspirational",
	"Inspiring (inspirational)",
	"intimate",
	"introspective",
	"Jew's-harp (jewsharp)",
	"jewsharp",
	"joyful (happy)",
	"Kalimba",
	"Kanun",
	"Kazoo",
	"Keyboard (synthesizer)",
	"keyboardinstrument (synthesizer)",
	"keyboards (synthesizer)",
	"keys (synthesizer)",
	"klavier (piano)",
	"Kora",
	"Koto",
	"likembe (mbira)",
	"Lute",
	"majestic",
	"Mandola",
	"Mandolin",
	"mandolina (mandolin)",
	"mandoline (mandolin)",
	"marã&shy;mbula (kalimba)",
	"Marimba",
	"mbira",
	"Mbira (kalimba)",
	"Meditative",
	"melancholic",
	"Melancholy (melancholic)",
	"melancolic (melancholic)",
	"melancolique (melancholic)",
	"Mellophone",
	"Mellotron",
	"Melodica",
	"Metallophone",
	"motivation (motivational)",
	"Motivational",
	"musicalsaw",
	"Ney",
	"Nostalgic",
	"nyckelharpa",
	"Oboe",
	"Ocarina",
	"orchestra",
	"Organ",
	"Oud",
	"Pan Flute (panflute)",
	"Pandeiro",
	"panflute",
	"Peaceful",
	"Percussion",
	"percussions (percussion)",
	"Piano",
	"pianoforte (piano)",
	"pianos (piano)",
	"Piccolo",
	"Pipe Organ (organ)",
	"pipeorgan",
	"positive (upbeat)",
	"powerful",
	"quirky",
	"rainstick",
	"relax (peaceful)",
	"relaxant (peaceful)",
	"relaxation (peaceful)",
	"Relaxed (peaceful)",
	"Relaxing",
	"Relaxing (peaceful)",
	"romance (romantic)",
	"Romantic",
	"romantique (romantic)",
	"Sad",
	"Sampler",
	"santoor (santur)",
	"Santur",
	"sarangi",
	"satirical",
	"sax (saxophone)",
	"Saxophone",
	"scary",
	"sensual (sexy)",
	"sentimental",
	"serene",
	"sexy",
	"shaker",
	"Shamisen",
	"Shekere",
	"Singing bowl (singingbowl)",
	"singingbowl",
	"Sitar",
	"Slide Guitar (slideguitar)",
	"slideguitar",
	"solemn",
	"steel-stringacousticguitar (acousticguitar)",
	"steelguitar (slideguitar)",
	"Steelpan",
	"strange",
	"string (strings)",
	"strings",
	"surdo",
	"synth (synthesizer)",
	"synthe (synthesizer)",
	"Synthesizer",
	"synthesizers (synthesizer)",
	"synthetiseur (synthesizer)",
	"synthetiseurs (synthesizer)",
	"synthetizer (synthesizer)",
	"synths (synthesizer)",
	"Tambourine",
	"Tambura",
	"tamtam",
	"Tamtam (gong)",
	"tender",
	"tense",
	"theatrical",
	"Theremin",
	"thermin (theremin)",
	"tibetan bowls (tibetanbowls)",
	"tibetanbowls",
	"Timpani",
	"tinwhistle",
	"Triangle",
	"trippy",
	"Trombone",
	"trompette (trumpet)",
	"Trumpet",
	"Tuba",
	"tubularbell",
	"Udu",
	"Ukulele",
	"upbeat",
	"Uplifting",
	"veryhappy",
	"verysad",
	"Vibraphone",
	"Viola",
	"Violin",
	"violine (violin)",
	"violino (violin)",
	"violins (violin)",
	"violon (violin)",
	"violoncelle (cello)",
	"violons (violin)",
	"vocoder",
	"Washboard",
	"Weird (strange)",
	"whistling",
	"Wind",
	"woodblock",
	"woodwind",
	"Xylophone",
	"zen (meditative)",
}

type FieldType int

const (
	Genre FieldType = iota
	Tag
)

func toLookup(kv map[string]string) map[string]string {
	var keys []string
	for k := range kv {
		keys = append(keys, k)
	}
	m := map[string]string{}
	for _, s := range keys {
		m[strings.ToLower(s)] = s
		m[s] = s
	}
	return m
}

func GetField(v string) (string, FieldType, bool) {
	genreLookup := toLookup(genreValues)
	tagLookup := toLookup(tagValues)
	v = strings.ToLower(v)
	// Use conversion when available
	if val, ok := convert[v]; ok && val != "" {
		v = val
	}
	v1 := v
	v2 := strings.ReplaceAll(v, " ", "")
	for _, v := range []string{v1, v2} {
		if _, ok := genreLookup[v]; ok {
			return genreLookup[v], Genre, true
		}
		if _, ok := tagLookup[v]; ok {
			return tagLookup[v], Tag, true
		}
	}
	return "", 0, false
}

var convert = map[string]string{
	// genres
	"alternative rock":  "alternativerock",
	"chill":             "Chillout",
	"easy listening":    "easylistening",
	"electro":           "Electronic",
	"fusion":            "jazzfusion",
	"heavy metal":       "heavymetal",
	"indie rock":        "indierock",
	"new age":           "newage",
	"new-age":           "newage",
	"pop rock":          "poprock",
	"progressive metal": "progressivemetal",
	"progressive rock":  "progressiverock",
	"r&b":               "rnb",
	// instruments
	"bass guitar":       "Bass",
	"brass instruments": "brass",
	"brass section":     "brass",
	"drum machine":      "drummachine",
	"electric guitar":   "Electric Guitar (electricguitar)",
	"electric piano":    "electricpiano",
	"keyboard":          "Keyboard (synthesizer)",
	"keyboards":         "keyboards (synthesizer)",
	"synth":             "synth (synthesizer)",
	"bass synth":        "Bass",
	"bass synthesizer":  "Bass",
	"electronic drums":  "drummachine",
	"sequencer":         "synth (synthesizer)",
	// moods
	"adventurous":   "exciting",
	"contemplative": "introspective",
	"cool":          "groovy",
	"calming":       "Calm",
	"dynamic":       "dynamic (energetic)",
	"driving":       "energetic",
	"elegant":       "majestic",
	"enigmatic":     "Mystical",
	"ethereal":      "dreamy",
	"futuristic":    "computer",
	"hypnotic":      "meditative",
	"innovative":    "experimental",
	"intense":       "aggressive",
	"intriguing":    "Inspiring (inspirational)",
	"mellow":        "relaxing",
	"melancholy":    "melancholic",
	"mysterious":    "Weird (strange)",
	"playful":       "fun",
	"reflective":    "introspective",
	"relaxed":       "Relaxing",
	"seductive":     "sensual (sexy)",
	"sensual":       "sensual (sexy)",
	"smooth":        "Relaxing",
	"soothing":      "Ambient",
	"sophisticated": "majestic",
	"soulful":       "Emotion (emotional)",
	"spacey":        "Ambient",
	"sublime":       "Epic",
	"tranquil":      "Relaxing",
	"triumphant":    "Uplifting",
	// styles
	"abstract":                  "experimental",
	"acid jazz":                 "acidjazz",
	"acoustic":                  "",
	"acoustic blues":            "Blues",
	"acoustic guitar":           "guitar",
	"acoustic jazz":             "Jazz",
	"acoustic pop":              "Pop",
	"ambient electronic":        "Electronic",
	"ambient house":             "house",
	"ambient jazz":              "Jazz",
	"ambient pop":               "Pop",
	"atmospheric":               "Ambient",
	"background music":          "easylistening",
	"ballad":                    "romantic",
	"beautiful":                 "romantic",
	"big band":                  "",
	"blues fusion":              "Blues",
	"blues rock":                "bluesrock",
	"chamber jazz":              "Jazz",
	"chamber music":             "Classical",
	"chicago blues":             "Blues",
	"chill out":                 "Chillout",
	"chill-out":                 "Chillout",
	"cinematic":                 "filmscore",
	"classical crossover":       "Classical",
	"contemporary":              "",
	"contemporary classical":    "Classical",
	"contemporary instrumental": "",
	"contemporary jazz":         "Jazz",
	"cool jazz":                 "Jazz",
	"deep house":                "deephouse",
	"delta blues":               "Blues",
	"doom metal":                "doom (doommetal)",
	"dream pop":                 "dreampop",
	"drum focused":              "Drums",
	"drum and bass":             "drumandbass (drumnbass)",
	"electric blues":            "Blues",
	"electro funk":              "electrofunk",
	"electronic jazz":           "Jazz",
	"electronic rock":           "Rock",
	"folk blues":                "Blues",
	"folk jazz":                 "Jazz",
	"folk rock":                 "Rock",
	"fusion jazz":               "Jazz",
	"future bass":               "futurebass",
	"gothic metal":              "gothic",
	"guitar jazz":               "Jazz",
	"guitar solo":               "guitar",
	"hard bop":                  "Jazz",
	"hard rock":                 "hardrock",
	"indie electronic":          "Electronic",
	"indie folk":                "Folk",
	"instrumental rock":         "Rock",
	"latin jazz":                "latinjazz",
	"lounge":                    "easylistening",
	"mellow jazz":               "Jazz",
	"minimal":                   "ambient",
	"minimalism":                "",
	"minimalist":                "",
	"modal jazz":                "Jazz",
	"neo-classical":             "Classical",
	"neo-soul":                  "Soul",
	"nu disco":                  "Disco",
	"nu jazz":                   "nujazz",
	"nu-disco":                  "Disco",
	"orchestral":                "orchestra",
	"piano blues":               "Blues",
	"piano jazz":                "Jazz",
	"piano rock":                "Rock",
	"post-rock":                 "postrock",
	"power metal":               "powermetal",
	"progressive":               "",
	"progressive electronic":    "Electronic",
	"psybient":                  "",
	"psychedelic":               "",
	"psychedelic rock":          "psychedelicrock",
	"ragtime jazz":              "Jazz",
	"retro":                     "",
	"retrowave":                 "synthwave",
	"sadcore":                   "Sad",
	"singer-songwriter":         "Singer-Songwriter (singersongwriter)",
	"smooth jazz":               "smoothjazz",
	"soft rock":                 "Rock",
	"soul jazz":                 "Jazz",
	"soulful blues":             "Blues",
	"space":                     "ambient",
	"space rock":                "spacerock",
	"symphonic metal":           "Metal",
	"thrash metal":              "thrash (thrashmetal)",
	"trip hop":                  "triphop",
	"trip-hop":                  "triphop",
	"acoustic rock":             "Rock",
	"instrumental":              "",
}

var tagValues = map[string]string{
	"Accordion":                            "56-1",
	"acousticbass":                         "1175966-2",
	"acousticbassguitar (acousticbass)":    "1175966-3",
	"acousticguitar":                       "16390-4",
	"aggressive":                           "290856",
	"alboka":                               "18068-6",
	"Alphorn":                              "16375-7",
	"alto (viola)":                         "10360-8",
	"angry":                                "1945349-9",
	"Bagpipes":                             "2473332",
	"baixo (bass)":                         "54-11",
	"bajo (bass)":                          "54-12",
	"Balafon":                              "11554-13",
	"Balalaika":                            "18066-14",
	"bandolim (mandolin)":                  "10881-15",
	"bandone (bandoneon)":                  "16379-16",
	"bandoneã³n (bandoneon)":               "16379-17",
	"Bandoneon":                            "16379-18",
	"Banjo":                                "12473-19",
	"Bass":                                 "54-20",
	"basse (bass)":                         "54-21",
	"bassguitar (bass)":                    "54-22",
	"Bassoon":                              "16370-23",
	"bateria (drums)":                      "1157745-24",
	"batterie (drums)":                     "1157745-25",
	"bazooka":                              "10984-26",
	"beatbox":                              "3655-27",
	"Bell (bells)":                         "6083-28",
	"bells":                                "6083-29",
	"Berimbau":                             "12423-30",
	"blissful (happy)":                     "1777-31",
	"bodhr (bodhran)":                      "17832-32",
	"bodhrã¡n (bodhran)":                   "17832-33",
	"Bodhran":                              "17832-34",
	"bombard (bombarde)":                   "16371-35",
	"Bombarde":                             "16371-36",
	"Bongo":                                "7314-37",
	"bongodrum (bongo)":                    "7314-38",
	"bongos (bongo)":                       "7314-39",
	"brass":                                "4040-40",
	"Bugle":                                "16376-41",
	"caj (cajon)":                          "426-42",
	"cajã³n (cajon)":                       "426-43",
	"Cajon":                                "426-44",
	"Calm":                                 "2110068-45",
	"Calm (peaceful)":                      "1276-46",
	"calme (peaceful)":                     "1276-47",
	"Carillon":                             "2076-48",
	"Castanets":                            "27945-49",
	"celesta":                              "2003584-50",
	"Cello":                                "384-51",
	"chapmanstick":                         "16384-52",
	"Charango":                             "5635-53",
	"cheerful":                             "1945995-54",
	"chitarra":                             "1162067-55",
	"Cimbalom":                             "16387-56",
	"Cittern":                              "16385-57",
	"claps":                                "32802-58",
	"Clarinet":                             "10781-59",
	"clarinette (clarinet)":                "10781-60",
	"classicalguitar":                      "16391-61",
	"clavecin (harpsichord)":               "8219-62",
	"Clavichord":                           "16386-63",
	"clavicordio (clavichord)":             "16386-64",
	"claviers (synthesizer)":               "3603-65",
	"Computer":                             "5103-66",
	"computers (computer)":                 "5103-67",
	"Concertina":                           "16380-68",
	"Conga":                                "7266-69",
	"congas (conga)":                       "7266-70",
	"contrabajo (doublebass)":              "6779-71",
	"contrebasse (doublebass)":             "6779-72",
	"Cowbell":                              "16399-73",
	"cu (cuica)":                           "18063-74",
	"cuã&shy;ca (cuica)":                   "18063-75",
	"cuica":                                "18063-76",
	"Cymbal":                               "8325-77",
	"Dark":                                 "335-78",
	"dholak":                               "18061-79",
	"Didgeridoo":                           "43-80",
	"Djembe":                               "1405-81",
	"Double Bass (doublebass)":             "6779-82",
	"doublebass":                           "6779-83",
	"dramatic":                             "1945133-84",
	"dreamy":                               "2541-85",
	"drole (funny)":                        "2177-86",
	"drum (drums)":                         "1157745-87",
	"drummachine":                          "8641-88",
	"Drums":                                "1157745-89",
	"duduk":                                "7724-90",
	"Dunun":                                "16529-91",
	"dynamic (energetic)":                  "5942-92",
	"Electric Guitar (electricguitar)":     "5316-93",
	"electricbass":                         "1158451-94",
	"electricguitar":                       "5316-95",
	"electricguitars (electricguitar)":     "5316-96",
	"electricorgan":                        "1170310-97",
	"electricpiano":                        "16410-98",
	"electro amplified (electroamplified)": "2109222-99",
	"electroamplified":                     "2109222-100",
	"electronicorgan":                      "16409-101",
	"Emotion (emotional)":                  "2754-102",
	"emotional":                            "2754-103",
	"Energetic":                            "5942-104",
	"energie (energetic)":                  "5942-105",
	"energy (energetic)":                   "5942-106",
	"Epic":                                 "3913-107",
	"Erhu":                                 "16524-108",
	"erotic":                               "1185313-109",
	"erotic (sexy)":                        "545-110",
	"euphonium":                            "18064-111",
	"exciting":                             "1946479-112",
	"Fiddle":                               "8017-113",
	"flauta (flute)":                       "5634-114",
	"flauto (flute)":                       "5634-115",
	"Flugelhorn":                           "16377-116",
	"Flute":                                "5634-117",
	"flutes (flute)":                       "5634-118",
	"fortepian (piano)":                    "35-119",
	"frenchhorn (horn)":                    "7758-120",
	"fun":                                  "319-121",
	"funny":                                "2177-122",
	"gã¼iro (guiro)":                       "7700-123",
	"gitarre":                              "1159760-124",
	"glassharmonica":                       "16400-125",
	"Glockenspiel":                         "3552-126",
	"gong":                                 "4303-127",
	"Groove (groovy)":                      "1498-128",
	"groovy":                               "1498-129",
	"Guiro":                                "7700-130",
	"guitar":                               "10748-131",
	"guitare (guitar)":                     "10748-132",
	"guitareelectrique (electricguitar)":   "5316-133",
	"guitares (guitar)":                    "10748-134",
	"guitarra (guitar)":                    "10748-135",
	"guitarras (guitar)":                   "10748-136",
	"guitars (guitar)":                     "10748-137",
	"Hammond":                              "8053-138",
	"hammondorgan (hammond)":               "8053-139",
	"hamonica (harmonica)":                 "432-140",
	"handpan":                              "1270380-141",
	"Happy":                                "1777-142",
	"Harmonica":                            "432-143",
	"Harmonium":                            "16381-144",
	"Harp":                                 "6066-145",
	"harpe (harp)":                         "6066-146",
	"Harpsichord":                          "8219-147",
	"Horn":                                 "7758-148",
	"horns (horn)":                         "7758-149",
	"inspiration (inspirational)":          "7558-150",
	"inspirational":                        "7558-151",
	"Inspiring (inspirational)":            "7558-152",
	"intimate":                             "1953577-153",
	"introspective":                        "5801-154",
	"Jew's-harp (jewsharp)":                "12422-155",
	"jewsharp":                             "12422-156",
	"joyful (happy)":                       "1777-157",
	"Kalimba":                              "7842-158",
	"Kanun":                                "16454-159",
	"Kazoo":                                "12489-160",
	"Keyboard (synthesizer)":               "3603-161",
	"keyboardinstrument (synthesizer)":     "3603-162",
	"keyboards (synthesizer)":              "3603-163",
	"keys (synthesizer)":                   "3603-164",
	"klavier (piano)":                      "35-165",
	"Kora":                                 "16392-166",
	"Koto":                                 "16393-167",
	"likembe (mbira)":                      "16527-168",
	"Lute":                                 "9292-169",
	"majestic":                             "18523-170",
	"Mandola":                              "16395-171",
	"Mandolin":                             "10881-172",
	"mandolina (mandolin)":                 "10881-173",
	"mandoline (mandolin)":                 "10881-174",
	"marã&shy;mbula (kalimba)":             "7842-175",
	"Marimba":                              "16402-176",
	"mbira":                                "16527-177",
	"Mbira (kalimba)":                      "7842-178",
	"Meditative":                           "4584-179",
	"melancholic":                          "3775-180",
	"Melancholy (melancholic)":             "3775-181",
	"melancolic (melancholic)":             "3775-182",
	"melancolique (melancholic)":           "3775-183",
	"Mellophone":                           "16378-184",
	"Mellotron":                            "2744-185",
	"Melodica":                             "16382-186",
	"Metallophone":                         "1059-187",
	"motivation (motivational)":            "46624-188",
	"Motivational":                         "46624-189",
	"musicalsaw":                           "16403-190",
	"Ney":                                  "7695-191",
	"Nostalgic":                            "6782-192",
	"nyckelharpa":                          "27941-193",
	"Oboe":                                 "10996-194",
	"Ocarina":                              "12166-195",
	"orchestra":                            "3085-196",
	"Organ":                                "3664-197",
	"Oud":                                  "16254-198",
	"Pan Flute (panflute)":                 "16367-199",
	"Pandeiro":                             "23633-200",
	"panflute":                             "16367-201",
	"Peaceful":                             "1276-202",
	"Percussion":                           "1306-203",
	"percussions (percussion)":             "1306-204",
	"Piano":                                "35-205",
	"pianoforte (piano)":                   "35-206",
	"pianos (piano)":                       "35-207",
	"Piccolo":                              "16368-208",
	"Pipe Organ (organ)":                   "3664-209",
	"pipeorgan":                            "16383-210",
	"positive (upbeat)":                    "1944454-211",
	"powerful":                             "1944171-212",
	"quirky":                               "16350-213",
	"rainstick":                            "1436440-214",
	"relax (peaceful)":                     "1276-215",
	"relaxant (peaceful)":                  "1276-216",
	"relaxation (peaceful)":                "1276-217",
	"Relaxed (peaceful)":                   "1276-218",
	"Relaxing":                             "2110064-219",
	"Relaxing (peaceful)":                  "1276-220",
	"romance (romantic)":                   "2820-221",
	"Romantic":                             "2820-222",
	"romantique (romantic)":                "2820-223",
	"Sad":                                  "3496-224",
	"Sampler":                              "475-225",
	"santoor (santur)":                     "16453-226",
	"Santur":                               "16453-227",
	"sarangi":                              "18062-228",
	"satirical":                            "10869-229",
	"sax (saxophone)":                      "44-230",
	"Saxophone":                            "44-231",
	"scary":                                "1952633-232",
	"sensual (sexy)":                       "545-233",
	"sentimental":                          "573-234",
	"serene":                               "6069-235",
	"sexy":                                 "545-236",
	"shaker":                               "1162756-237",
	"Shamisen":                             "18075-238",
	"Shekere":                              "16405-239",
	"Singing bowl (singingbowl)":           "27943-240",
	"singingbowl":                          "27943-241",
	"Sitar":                                "3847-242",
	"Slide Guitar (slideguitar)":           "860-243",
	"slideguitar":                          "860-244",
	"solemn":                               "55188-245",
	"steel-stringacousticguitar (acousticguitar)": "16390-246",
	"steelguitar (slideguitar)":                   "860-247",
	"Steelpan":                                    "16530-248",
	"strange":                                     "295-249",
	"string (strings)":                            "1613-250",
	"strings":                                     "1613-251",
	"surdo":                                       "8199-252",
	"synth (synthesizer)":                         "3603-253",
	"synthe (synthesizer)":                        "3603-254",
	"Synthesizer":                                 "3603-255",
	"synthesizers (synthesizer)":                  "3603-256",
	"synthetiseur (synthesizer)":                  "3603-257",
	"synthetiseurs (synthesizer)":                 "3603-258",
	"synthetizer (synthesizer)":                   "3603-259",
	"synths (synthesizer)":                        "3603-260",
	"Tambourine":                                  "16406-261",
	"Tambura":                                     "16455-262",
	"tamtam":                                      "49-263",
	"Tamtam (gong)":                               "4303-264",
	"tender":                                      "6312-265",
	"tense":                                       "13127-266",
	"theatrical":                                  "4890-267",
	"Theremin":                                    "18060-268",
	"thermin (theremin)":                          "18060-269",
	"tibetan bowls (tibetanbowls)":                "1862616-270",
	"tibetanbowls":                                "1862616-271",
	"Timpani":                                     "16398-272",
	"tinwhistle":                                  "18065-273",
	"Triangle":                                    "16407-274",
	"trippy":                                      "2536-275",
	"Trombone":                                    "58-276",
	"trompette (trumpet)":                         "2403-277",
	"Trumpet":                                     "2403-278",
	"Tuba":                                        "57-279",
	"tubularbell":                                 "16408-280",
	"Udu":                                         "16520-281",
	"Ukulele":                                     "1061-282",
	"upbeat":                                      "1944454-283",
	"Uplifting":                                   "3549-284",
	"veryhappy":                                   "1304360-285",
	"verysad":                                     "1292388-286",
	"Vibraphone":                                  "50-287",
	"Viola":                                       "10360-288",
	"Violin":                                      "19395-289",
	"violine (violin)":                            "19395-290",
	"violino (violin)":                            "19395-291",
	"violins (violin)":                            "19395-292",
	"violon (violin)":                             "19395-293",
	"violoncelle (cello)":                         "384-294",
	"violons (violin)":                            "19395-295",
	"vocoder":                                     "2200-296",
	"Washboard":                                   "18059-297",
	"Weird (strange)":                             "295-298",
	"whistling":                                   "47964-299",
	"Wind":                                        "11442-300",
	"woodblock":                                   "18073-301",
	"woodwind":                                    "39783-302",
	"Xylophone":                                   "51-303",
	"zen (meditative)":                            "4584-304",
}

var genreValues = map[string]string{
	"8bit":                                 "1713-0",
	"acidhouse":                            "2888705",
	"acidjazz":                             "80-2",
	"adultcontemporary":                    "53933-3",
	"African":                              "2225515",
	"afro (african)":                       "2225545",
	"afro-cuban jazz (afrocubanjazz)":      "1659366-6",
	"afrobeat":                             "147741",
	"afrocubanjazz":                        "1659366-8",
	"afropop":                              "43331-9",
	"Alternative Pop (alternativepop)":     "1638753",
	"alternativehiphop":                    "28912-11",
	"alternativemetal":                     "21181-12",
	"alternativepop":                       "6386-13",
	"alternativernb":                       "1781643-14",
	"alternativerock":                      "7592-15",
	"ambiance (ambient)":                   "362-16",
	"ambiant (ambient)":                    "362-17",
	"Ambient":                              "362-18",
	"ambientdub":                           "37037-19",
	"americana":                            "3212-20",
	"americannative":                       "2109919-21",
	"artrock":                              "7818-22",
	"Asian":                                "10215-23",
	"Avant-garde (avantgarde)":             "1293-24",
	"avantgarde":                           "1293-25",
	"bachata":                              "11132-26",
	"balkan":                               "6849-27",
	"baroque":                              "542-28",
	"batucada":                             "56322-29",
	"Bebop":                                "6-30",
	"blackmetal":                           "1231-31",
	"bluegrass":                            "3898-32",
	"Blues":                                "180-33",
	"bluesrock":                            "3233-34",
	"bluesy (blues)":                       "180-35",
	"bolero":                               "2408-36",
	"bossa (bossanova)":                    "5420-37",
	"bossanova":                            "5420-38",
	"Breakbeat":                            "541-39",
	"Breakcore":                            "2204-40",
	"britpop":                              "3904-41",
	"cabaret":                              "1690-42",
	"calypso":                              "8022-43",
	"Celtic":                               "537-44",
	"celtique (celtic)":                    "537-45",
	"chamber":                              "8864-46",
	"chansonfrancaise":                     "392-47",
	"chill (chillout)":                     "1834-48",
	"chillhop":                             "54549-49",
	"Chillout":                             "1834-50",
	"chillwave":                            "38916-51",
	"chiptune (8bit)":                      "1713-52",
	"choral":                               "2006774-53",
	"christian":                            "5267-54",
	"classic (classical)":                  "2777-55",
	"Classical":                            "2777-56",
	"classicrock":                          "11313-57",
	"classique (classical)":                "2777-58",
	"cocktail jazz (smoothjazz)":           "505-59",
	"cocktailjazz (smoothjazz)":            "505-60",
	"coldwave":                             "395-61",
	"contemporarypiano":                    "56524-62",
	"Corporate":                            "9782-63",
	"Country":                              "1953-64",
	"countryrock":                          "4489-65",
	"crust":                                "8066-66",
	"cumbia":                               "2112-67",
	"Dance":                                "100-68",
	"Dancehall":                            "2405-69",
	"dancepop":                             "1966907-70",
	"Dark Wave (darkwave)":                 "283-71",
	"darkambient":                          "363-72",
	"darkstep":                             "17330-73",
	"darkwave":                             "283-74",
	"death (deathmetal)":                   "1763-75",
	"deathcore":                            "5352-76",
	"deathmetal":                           "1763-77",
	"deephouse":                            "2054-78",
	"Disco":                                "88-79",
	"dnb (drumnbass)":                      "515-80",
	"doom (doommetal)":                     "22769-81",
	"doommetal":                            "22769-82",
	"Downtempo":                            "316-83",
	"dreampop":                             "442-84",
	"Drone":                                "2245-85",
	"drumandbass (drumnbass)":              "515-86",
	"drumbass (drumnbass)":                 "515-87",
	"drumnbass":                            "515-88",
	"Dub":                                  "10-89",
	"Dubstep":                              "8618-90",
	"Easy-listening (easylistening)":       "1945950-91",
	"easylistening":                        "1945950-92",
	"EBM":                                  "3907-93",
	"EDM":                                  "5941-94",
	"electrofunk":                          "2293-95",
	"electrohouse":                         "6795-96",
	"Electronic":                           "327-97",
	"electronica":                          "752366-98",
	"electronik (electronic)":              "327-99",
	"electronique (electronic)":            "327-100",
	"Electropop":                           "357-101",
	"electropunk":                          "263-102",
	"electrorock":                          "407-103",
	"electroswing":                         "37227-104",
	"elettronica (electronic)":             "327-105",
	"emo":                                  "1249-106",
	"Eurodance":                            "1717-107",
	"Experimental":                         "12608-108",
	"experimentale (experimental)":         "12608-109",
	"fado":                                 "3052-110",
	"fanfare":                              "2884-111",
	"filmscore":                            "1954332-112",
	"Flamenco":                             "509-113",
	"Folk":                                 "69-114",
	"folklore":                             "2272-115",
	"freejazz":                             "415-116",
	"frenchpop":                            "11376-117",
	"Funk":                                 "141-118",
	"funky (funk)":                         "141-119",
	"futurebass":                           "50151-120",
	"gangsta (gangstarap)":                 "13951-121",
	"gangstarap":                           "13951-122",
	"Garage":                               "492-123",
	"Gipsy (gypsy)":                        "9380-124",
	"glam":                                 "3784-125",
	"Glitch":                               "1267-126",
	"Gospel":                               "64-127",
	"Gothic":                               "1843-128",
	"gothique (gothic)":                    "1843-129",
	"grime":                                "9083-130",
	"grind (grindcore)":                    "1230-131",
	"Grindcore":                            "1230-132",
	"groovemetal":                          "25981-133",
	"Grunge":                               "81-134",
	"Gypsy":                                "9380-135",
	"Hardcore":                             "67-136",
	"hardcorepunk":                         "9910-137",
	"hardrock":                             "1944554-138",
	"hardstep":                             "5152-139",
	"heavymetal":                           "1764-140",
	"hiphop":                               "39-141",
	"House":                                "414-142",
	"IDM":                                  "344-143",
	"indian":                               "3302-144",
	"Indie":                                "444-145",
	"indiepop":                             "3550-146",
	"indierock":                            "1187328-147",
	"indierock (indie)":                    "444-148",
	"indietronica":                         "6791-149",
	"Industrial":                           "827-150",
	"industrialmetal":                      "22499-151",
	"industrialrock":                       "24769-152",
	"intro":                                "3763-153",
	"Jazz Rap (jazzrap)":                   "58166-155",
	"jazzfunk":                             "1263-156",
	"jazzfusion":                           "84-157",
	"jazzrap":                              "58166-158",
	"Jingle":                               "16128-159",
	"jpop":                                 "10356-160",
	"Jungle":                               "640-161",
	"Kids/Quirky (kidsquirky)":             "2110065-162",
	"kidsquirky":                           "2110065-163",
	"klezmer":                              "8209-164",
	"kpop":                                 "21973-165",
	"krautrock":                            "3288-166",
	"Latin":                                "1925-167",
	"latinjazz":                            "22289-168",
	"latino (latin)":                       "1925-169",
	"lofi":                                 "445-170",
	"logo":                                 "52356-171",
	"loop":                                 "3517-172",
	"mambo":                                "8024-173",
	"Manouche":                             "1718-174",
	"march":                                "5314-175",
	"mariachi":                             "49729-176",
	"mathcore":                             "16671-177",
	"mathrock":                             "7138-178",
	"medieval":                             "686-179",
	"merengue":                             "5628-180",
	"Metal":                                "25-181",
	"Metalcore":                            "6389-182",
	"middleeastern":                        "24742-183",
	"musicbed":                             "1675730-184",
	"nativeamerican (americannative)":      "2109919-185",
	"neoclassical":                         "6064-186",
	"neurofunk":                            "17513-187",
	"newage":                               "114-188",
	"newwave":                              "616-189",
	"noisepop":                             "10474-190",
	"noiserock":                            "10117-191",
	"nujazz":                               "2203-192",
	"numetal":                              "4318-193",
	"opera":                                "193-194",
	"Oriental":                             "969-195",
	"Pop":                                  "5-196",
	"Pop Rock (poprock)":                   "1946575-197",
	"poppunk":                              "2283-198",
	"poprock":                              "1946575-199",
	"postgrunge":                           "3400-200",
	"posthardcore":                         "9949-201",
	"postmetal":                            "9948-202",
	"postpunk":                             "4022-203",
	"postrock":                             "270-204",
	"powermetal":                           "3476-205",
	"production":                           "6187-206",
	"progressive rock (progressiverock)":   "4683-207",
	"progressivehouse":                     "5132-208",
	"progressivemetal":                     "6215-209",
	"progressiverock":                      "4683-210",
	"psychedelicrock":                      "22503-211",
	"Psytrance":                            "1454-212",
	"Punk":                                 "33-213",
	"Ragga":                                "552-214",
	"raggae (reggae)":                      "9-215",
	"ragtime":                              "6999-216",
	"rai":                                  "678-217",
	"rap":                                  "11-218",
	"Rap (hiphop)":                         "39-219",
	"Reggae":                               "9-220",
	"reggaeton":                            "8034-221",
	"rhythmandblues (rnb)":                 "65-222",
	"rnb":                                  "65-223",
	"Rock":                                 "23-224",
	"rockabilly":                           "11072-225",
	"rockandroll (rocknroll)":              "32-226",
	"rockindependant (indie)":              "444-227",
	"rocknroll":                            "32-228",
	"rocksteady":                           "971-229",
	"rumba":                                "280-230",
	"salsa":                                "1386-231",
	"Samba":                                "5101-232",
	"shoegaze":                             "5138-233",
	"Singer-Songwriter (singersongwriter)": "833-234",
	"singersongwriter":                     "833-235",
	"Ska":                                  "94-236",
	"skapunk":                              "3201-237",
	"sludge":                               "7830-238",
	"songwriter (singersongwriter)":        "833-240",
	"songwriting (singersongwriter)":       "833-241",
	"Soul":                                 "1214-242",
	"Soundtrack (filmscore)":               "1954332-243",
	"southernrock":                         "7300-244",
	"spacerock":                            "7591-245",
	"sperimental (experimental)":           "12608-246",
	"sperimentale (experimental)":          "12608-247",
	"spokenword":                           "2901-248",
	"stinger":                              "41105-249",
	"stoner":                               "1461-250",
	"surf (surfrock)":                      "13734-251",
	"surfrock":                             "13734-252",
	"swing":                                "1820-253",
	"Symphonic":                            "879-254",
	"symphonique (symphonic)":              "879-255",
	"Synthpop":                             "828-256",
	"synthwave":                            "49386-257",
	"Tango":                                "90-258",
	"Techno":                               "29-259",
	"thrash (thrashmetal)":                 "5509-260",
	"thrashmetal":                          "5509-261",
	"Trailer":                              "13364-262",
	"trailermusic (trailer)":               "13364-263",
	"Trance":                               "41-264",
	"trap":                                 "34213-265",
	"trash (thrashmetal)":                  "5509-266",
	"trashmetal (thrashmetal)":             "5509-267",
	"Tribal":                               "1788-268",
	"tribe (tribal)":                       "1788-269",
	"triphop":                              "28-270",
	"tropicalhouse":                        "27441-271",
	"waltz":                                "8926-272",
	"Western":                              "6000-273",
	"World":                                "21-274",
	"worldmusic (world)":                   "21-275",
	"zouk":                                 "949-276",
}
